/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "F:\\我的项目\\测试vue按需导入问题\\my-vue-press\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "F:\\我的项目\\测试vue按需导入问题\\my-vue-press\\node_modules\\@vuepress\\plugin-nprogress\\clientRootMixin.js"
import m2 from "F:\\我的项目\\测试vue按需导入问题\\my-vue-press\\node_modules\\@vuepress\\plugin-active-header-links\\clientRootMixin.js"
import m3 from "F:\\我的项目\\测试vue按需导入问题\\my-vue-press\\node_modules\\vuepress-plugin-code-copy\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2,
  m3
]