/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "F:\\我的项目\\测试vue按需导入问题\\my-vue-press\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-617164b1",
    path: "/dayRecord/heart/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-617164b1").then(next)
    },
  },
  {
    path: "/dayRecord/heart/index.html",
    redirect: "/dayRecord/heart/"
  },
  {
    name: "v-e0f072fe",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e0f072fe").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-c6f917b8",
    path: "/language/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c6f917b8").then(next)
    },
  },
  {
    path: "/language/index.html",
    redirect: "/language/"
  },
  {
    name: "v-c344d332",
    path: "/language/chinese.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c344d332").then(next)
    },
  },
  {
    name: "v-7d5e92be",
    path: "/language/english.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d5e92be").then(next)
    },
  },
  {
    name: "v-ef71bfea",
    path: "/myProject/chartRoom/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ef71bfea").then(next)
    },
  },
  {
    path: "/myProject/chartRoom/index.html",
    redirect: "/myProject/chartRoom/"
  },
  {
    name: "v-0983b1aa",
    path: "/myProject/chartRoom/socketIo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0983b1aa").then(next)
    },
  },
  {
    name: "v-6d369030",
    path: "/myProject/chartRoom/webBuild.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d369030").then(next)
    },
  },
  {
    name: "v-b39fbf78",
    path: "/vuePress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b39fbf78").then(next)
    },
  },
  {
    path: "/vuePress/index.html",
    redirect: "/vuePress/"
  },
  {
    name: "v-284ff21d",
    path: "/vuePress/componentGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-284ff21d").then(next)
    },
  },
  {
    path: "/vuePress/componentGuide/index.html",
    redirect: "/vuePress/componentGuide/"
  },
  {
    name: "v-9869b006",
    path: "/vuePress/gitOpreation/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9869b006").then(next)
    },
  },
  {
    path: "/vuePress/gitOpreation/index.html",
    redirect: "/vuePress/gitOpreation/"
  },
  {
    name: "v-3918cf77",
    path: "/vuePress/githubFBGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3918cf77").then(next)
    },
  },
  {
    path: "/vuePress/githubFBGuide/index.html",
    redirect: "/vuePress/githubFBGuide/"
  },
  {
    name: "v-624eab97",
    path: "/vuePress/navigationGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-624eab97").then(next)
    },
  },
  {
    path: "/vuePress/navigationGuide/index.html",
    redirect: "/vuePress/navigationGuide/"
  },
  {
    name: "v-6bc56a52",
    path: "/vuePress/pwaGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6bc56a52").then(next)
    },
  },
  {
    path: "/vuePress/pwaGuide/index.html",
    redirect: "/vuePress/pwaGuide/"
  },
  {
    name: "v-062ab3ca",
    path: "/vuePress/sidebarGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-062ab3ca").then(next)
    },
  },
  {
    path: "/vuePress/sidebarGuide/index.html",
    redirect: "/vuePress/sidebarGuide/"
  },
  {
    name: "v-fcb9dbd2",
    path: "/vuePress/vendorGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcb9dbd2").then(next)
    },
  },
  {
    path: "/vuePress/vendorGuide/index.html",
    redirect: "/vuePress/vendorGuide/"
  },
  {
    name: "v-f3157192",
    path: "/vuePress/vuePressGuide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3157192").then(next)
    },
  },
  {
    path: "/vuePress/vuePressGuide/index.html",
    redirect: "/vuePress/vuePressGuide/"
  },
  {
    name: "v-f0aafb38",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0aafb38").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    name: "v-362640e9",
    path: "/web/css/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-362640e9").then(next)
    },
  },
  {
    path: "/web/css/index.html",
    redirect: "/web/css/"
  },
  {
    name: "v-68562cfb",
    path: "/web/echarts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68562cfb").then(next)
    },
  },
  {
    path: "/web/echarts/index.html",
    redirect: "/web/echarts/"
  },
  {
    name: "v-2892f851",
    path: "/web/element-ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2892f851").then(next)
    },
  },
  {
    path: "/web/element-ui/index.html",
    redirect: "/web/element-ui/"
  },
  {
    name: "v-014b2535",
    path: "/web/hosp-ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-014b2535").then(next)
    },
  },
  {
    path: "/web/hosp-ui/index.html",
    redirect: "/web/hosp-ui/"
  },
  {
    name: "v-5240c7cc",
    path: "/web/hosp-ui/componentEnvInig.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5240c7cc").then(next)
    },
  },
  {
    name: "v-3cf4cee4",
    path: "/web/hosp-ui/configInit.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3cf4cee4").then(next)
    },
  },
  {
    name: "v-5a9ff5e0",
    path: "/web/hosp-ui/css.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5a9ff5e0").then(next)
    },
  },
  {
    name: "v-647f3e80",
    path: "/web/hosp-ui/example.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-647f3e80").then(next)
    },
  },
  {
    name: "v-16b73c48",
    path: "/web/hosp-ui/monorepo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16b73c48").then(next)
    },
  },
  {
    name: "v-20598c00",
    path: "/web/hosp-ui/start.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-20598c00").then(next)
    },
  },
  {
    name: "v-6e6ebea0",
    path: "/web/hosp-ui/utils.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e6ebea0").then(next)
    },
  },
  {
    name: "v-5d059351",
    path: "/web/javascript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d059351").then(next)
    },
  },
  {
    path: "/web/javascript/index.html",
    redirect: "/web/javascript/"
  },
  {
    name: "v-ddf8f6de",
    path: "/web/nodejs/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ddf8f6de").then(next)
    },
  },
  {
    path: "/web/nodejs/index.html",
    redirect: "/web/nodejs/"
  },
  {
    name: "v-94d9fca2",
    path: "/web/plugins/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-94d9fca2").then(next)
    },
  },
  {
    path: "/web/plugins/index.html",
    redirect: "/web/plugins/"
  },
  {
    name: "v-bf18153a",
    path: "/web/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bf18153a").then(next)
    },
  },
  {
    path: "/web/vue/index.html",
    redirect: "/web/vue/"
  },
  {
    name: "v-5297e571",
    path: "/web/webDescription/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5297e571").then(next)
    },
  },
  {
    path: "/web/webDescription/index.html",
    redirect: "/web/webDescription/"
  },
  {
    name: "v-6573ad15",
    path: "/web/webpack/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6573ad15").then(next)
    },
  },
  {
    path: "/web/webpack/index.html",
    redirect: "/web/webpack/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]