/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "花小宝",
  "description": "Just playing around",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/assets/img/avatar.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#409eff"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "link",
      {
        "rel": "apple-touch-icon",
        "href": "/icons/bg.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "mask-icon",
        "href": "/icons/bg.jpg",
        "color": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/icons/bg.jpg"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#409eff"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/assets/img/avatar.jpg",
        "heroText": "welecom to 花小宝的 vuepress",
        "tagline": "vuepress 使用指南",
        "actionText": "快速搭建 vuepress →",
        "actionLink": "/vuePress/",
        "features": [
          {
            "title": "vuepress",
            "details": "是不是很羡慕别人文档网站搭建的这么好，没错，我也羡慕，当然，我已经知道怎么操作了，so,你是不是会骂我，别急啦，xiongdie 上面有个按钮，教程已经为你准备好了啦，跟着走，你也能这么牛逼！"
          },
          {
            "title": "前端",
            "details": "前端文档都会在记录在这里"
          },
          {
            "title": "杂技",
            "details": "分不清类别的，都放在这儿吧，懒得折腾！"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2023.07 - 现在    花小宝"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-e0f072fe",
      "path": "/",
      "lastUpdated": "2023年8月6日",
      "lastUpdatedTimestamp": 1691334975000
    },
    {
      "title": "欢迎进入语言配置栏，这里即将为你介绍，多彩的语言环境",
      "frontmatter": {},
      "regularPath": "/language/",
      "relativePath": "language/README.md",
      "key": "v-c6f917b8",
      "path": "/language/",
      "headers": [
        {
          "level": 3,
          "title": "欢迎进入语言配置栏，这里即将为你介绍，多彩的语言环境",
          "slug": "欢迎进入语言配置栏-这里即将为你介绍-多彩的语言环境"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "frontmatter": {},
      "regularPath": "/dayRecord/heart/",
      "relativePath": "dayRecord/heart/README.md",
      "key": "v-617164b1",
      "path": "/dayRecord/heart/",
      "lastUpdated": "2023年8月5日",
      "lastUpdatedTimestamp": 1691250484000
    },
    {
      "title": "中文",
      "frontmatter": {},
      "regularPath": "/language/chinese.html",
      "relativePath": "language/chinese.md",
      "key": "v-c344d332",
      "path": "/language/chinese.html",
      "headers": [
        {
          "level": 2,
          "title": "中文",
          "slug": "中文"
        }
      ],
      "lastUpdated": "2023年7月26日",
      "lastUpdatedTimestamp": 1690370617000
    },
    {
      "title": "English",
      "frontmatter": {},
      "regularPath": "/language/english.html",
      "relativePath": "language/english.md",
      "key": "v-7d5e92be",
      "path": "/language/english.html",
      "headers": [
        {
          "level": 2,
          "title": "English",
          "slug": "english"
        }
      ],
      "lastUpdated": "2023年7月26日",
      "lastUpdatedTimestamp": 1690370617000
    },
    {
      "title": "引入 vue 组件",
      "frontmatter": {
        "title": "引入 vue 组件"
      },
      "regularPath": "/vuePress/componentGuide/",
      "relativePath": "vuePress/componentGuide/README.md",
      "key": "v-284ff21d",
      "path": "/vuePress/componentGuide/",
      "headers": [
        {
          "level": 2,
          "title": "组件引入",
          "slug": "组件引入"
        }
      ],
      "lastUpdated": "2023年8月6日",
      "lastUpdatedTimestamp": 1691334975000
    },
    {
      "title": "vuepress 使用",
      "frontmatter": {
        "title": "vuepress 使用"
      },
      "regularPath": "/vuePress/",
      "relativePath": "vuePress/README.md",
      "key": "v-b39fbf78",
      "path": "/vuePress/",
      "headers": [
        {
          "level": 2,
          "title": "俗话说，工欲善其事必先利其器",
          "slug": "俗话说-工欲善其事必先利其器"
        },
        {
          "level": 3,
          "title": "markdown",
          "slug": "markdown"
        },
        {
          "level": 3,
          "title": "front matter",
          "slug": "front-matter"
        }
      ],
      "lastUpdated": "2023年8月7日",
      "lastUpdatedTimestamp": 1691423488000
    },
    {
      "title": "git 操作",
      "frontmatter": {},
      "regularPath": "/vuePress/gitOpreation/",
      "relativePath": "vuePress/gitOpreation/README.md",
      "key": "v-9869b006",
      "path": "/vuePress/gitOpreation/",
      "headers": [
        {
          "level": 2,
          "title": "git 操作",
          "slug": "git-操作"
        }
      ],
      "lastUpdated": "2023年8月8日",
      "lastUpdatedTimestamp": 1691509746000
    },
    {
      "title": "PWA 离线缓存",
      "frontmatter": {
        "title": "PWA 离线缓存"
      },
      "regularPath": "/vuePress/pwaGuide/",
      "relativePath": "vuePress/pwaGuide/README.md",
      "key": "v-6bc56a52",
      "path": "/vuePress/pwaGuide/",
      "headers": [
        {
          "level": 2,
          "title": "PWA 插件",
          "slug": "pwa-插件"
        },
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "使用",
          "slug": "使用"
        },
        {
          "level": 2,
          "title": "兼容处理",
          "slug": "兼容处理"
        }
      ],
      "lastUpdated": "2023年8月8日",
      "lastUpdatedTimestamp": 1691509746000
    },
    {
      "title": "github 部署",
      "frontmatter": {
        "title": "github 部署"
      },
      "regularPath": "/vuePress/githubFBGuide/",
      "relativePath": "vuePress/githubFBGuide/README.md",
      "key": "v-3918cf77",
      "path": "/vuePress/githubFBGuide/",
      "headers": [
        {
          "level": 2,
          "title": "发布到 github.io",
          "slug": "发布到-github-io"
        },
        {
          "level": 2,
          "title": "修改 config.js 文件",
          "slug": "修改-config-js-文件"
        },
        {
          "level": 2,
          "title": "新增 deploy.sh 文件",
          "slug": "新增-deploy-sh文件"
        },
        {
          "level": 2,
          "title": "新增 package.json 脚本",
          "slug": "新增-package-json-脚本"
        },
        {
          "level": 2,
          "title": "github 仓库设置",
          "slug": "github-仓库设置"
        },
        {
          "level": 2,
          "title": "效果",
          "slug": "效果"
        }
      ],
      "lastUpdated": "2023年8月8日",
      "lastUpdatedTimestamp": 1691509746000
    },
    {
      "title": "导航栏配置",
      "frontmatter": {
        "title": "导航栏配置",
        "sidebarDepth": 3,
        "tags": [
          "配置",
          "主题",
          "索引"
        ]
      },
      "regularPath": "/vuePress/navigationGuide/",
      "relativePath": "vuePress/navigationGuide/README.md",
      "key": "v-624eab97",
      "path": "/vuePress/navigationGuide/",
      "headers": [
        {
          "level": 2,
          "title": "导航栏 logo",
          "slug": "导航栏-logo"
        },
        {
          "level": 2,
          "title": "导航栏搜索框 (暂时没有配置，后续补充)",
          "slug": "导航栏搜索框-暂时没有配置-后续补充"
        },
        {
          "level": 2,
          "title": "导航栏链接配置",
          "slug": "导航栏链接配置"
        },
        {
          "level": 2,
          "title": "导航栏链接嵌套",
          "slug": "导航栏链接嵌套"
        },
        {
          "level": 2,
          "title": "导航栏禁用",
          "slug": "导航栏禁用"
        }
      ],
      "lastUpdated": "2023年8月5日",
      "lastUpdatedTimestamp": 1691250484000
    },
    {
      "title": "侧边栏配置",
      "frontmatter": {
        "title": "侧边栏配置",
        "sidebarDepth": 3
      },
      "regularPath": "/vuePress/sidebarGuide/",
      "relativePath": "vuePress/sidebarGuide/README.md",
      "key": "v-062ab3ca",
      "path": "/vuePress/sidebarGuide/",
      "headers": [
        {
          "level": 2,
          "title": "",
          "slug": ""
        },
        {
          "level": 2,
          "title": "基本配置",
          "slug": "基本配置"
        },
        {
          "level": 2,
          "title": "侧边栏分组",
          "slug": "侧边栏分组"
        },
        {
          "level": 2,
          "title": "多个侧边栏",
          "slug": "多个侧边栏"
        },
        {
          "level": 2,
          "title": "自动生成侧边栏",
          "slug": "自动生成侧边栏"
        },
        {
          "level": 2,
          "title": "禁用侧边栏",
          "slug": "禁用侧边栏"
        }
      ],
      "lastUpdated": "2023年8月5日",
      "lastUpdatedTimestamp": 1691207118000
    },
    {
      "title": "引入组件库",
      "frontmatter": {
        "title": "引入组件库"
      },
      "regularPath": "/vuePress/vendorGuide/",
      "relativePath": "vuePress/vendorGuide/README.md",
      "key": "v-fcb9dbd2",
      "path": "/vuePress/vendorGuide/",
      "headers": [
        {
          "level": 2,
          "title": "引入 第三方组件或者插件",
          "slug": "引入-第三方组件或者插件"
        },
        {
          "level": 2,
          "title": "关于 enhanceApp.js 文件",
          "slug": "关于-enhanceapp-js-文件"
        }
      ],
      "lastUpdated": "2023年8月7日",
      "lastUpdatedTimestamp": 1691423488000
    },
    {
      "title": "webpack",
      "frontmatter": {},
      "regularPath": "/web/",
      "relativePath": "web/README.md",
      "key": "v-f0aafb38",
      "path": "/web/",
      "headers": [
        {
          "level": 2,
          "title": "webpack",
          "slug": "webpack"
        },
        {
          "level": 3,
          "title": "webpac 发展史",
          "slug": "webpac-发展史"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "vueprss 初体验",
      "frontmatter": {
        "title": "vueprss 初体验"
      },
      "regularPath": "/vuePress/vuePressGuide/",
      "relativePath": "vuePress/vuePressGuide/README.md",
      "key": "v-f3157192",
      "path": "/vuePress/vuePressGuide/",
      "lastUpdated": "2023年8月7日",
      "lastUpdatedTimestamp": 1691423488000
    },
    {
      "title": "css",
      "frontmatter": {},
      "regularPath": "/web/css/",
      "relativePath": "web/css/README.md",
      "key": "v-362640e9",
      "path": "/web/css/",
      "headers": [
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "css 类型",
          "slug": "css-类型"
        },
        {
          "level": 3,
          "title": "css 简介",
          "slug": "css-简介"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "eleemnt-ui",
      "frontmatter": {},
      "regularPath": "/web/element-ui/",
      "relativePath": "web/element-ui/README.md",
      "key": "v-2892f851",
      "path": "/web/element-ui/",
      "headers": [
        {
          "level": 2,
          "title": "eleemnt-ui",
          "slug": "eleemnt-ui"
        },
        {
          "level": 3,
          "title": "官网",
          "slug": "官网"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "概述",
      "frontmatter": {},
      "regularPath": "/web/javascript/",
      "relativePath": "web/javascript/README.md",
      "key": "v-5d059351",
      "path": "/web/javascript/",
      "headers": [
        {
          "level": 2,
          "title": "概述",
          "slug": "概述"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "echaarts 图表",
      "frontmatter": {},
      "regularPath": "/web/echarts/",
      "relativePath": "web/echarts/README.md",
      "key": "v-68562cfb",
      "path": "/web/echarts/",
      "headers": [
        {
          "level": 2,
          "title": "echaarts 图表",
          "slug": "echaarts-图表"
        },
        {
          "level": 3,
          "title": "使用概述",
          "slug": "使用概述"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "nodejs",
      "frontmatter": {},
      "regularPath": "/web/nodejs/",
      "relativePath": "web/nodejs/README.md",
      "key": "v-ddf8f6de",
      "path": "/web/nodejs/",
      "headers": [
        {
          "level": 2,
          "title": "nodejs",
          "slug": "nodejs"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "plugins",
      "frontmatter": {},
      "regularPath": "/web/plugins/",
      "relativePath": "web/plugins/README.md",
      "key": "v-94d9fca2",
      "path": "/web/plugins/",
      "headers": [
        {
          "level": 2,
          "title": "plugins",
          "slug": "plugins"
        },
        {
          "level": 3,
          "title": "音乐插件",
          "slug": "音乐插件"
        }
      ],
      "lastUpdated": "2023年8月12日",
      "lastUpdatedTimestamp": 1691854023000
    },
    {
      "title": "vue",
      "frontmatter": {},
      "regularPath": "/web/vue/",
      "relativePath": "web/vue/README.md",
      "key": "v-bf18153a",
      "path": "/web/vue/",
      "headers": [
        {
          "level": 3,
          "title": "vue",
          "slug": "vue"
        }
      ],
      "lastUpdated": "2023年8月5日",
      "lastUpdatedTimestamp": 1691250484000
    },
    {
      "title": "webpack",
      "frontmatter": {},
      "regularPath": "/web/webpack/",
      "relativePath": "web/webpack/README.md",
      "key": "v-6573ad15",
      "path": "/web/webpack/",
      "headers": [
        {
          "level": 2,
          "title": "webpack",
          "slug": "webpack"
        },
        {
          "level": 3,
          "title": "webpack 坚决",
          "slug": "webpack-坚决"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    },
    {
      "title": "前端部署",
      "frontmatter": {},
      "regularPath": "/web/webDescription/",
      "relativePath": "web/webDescription/README.md",
      "key": "v-5297e571",
      "path": "/web/webDescription/",
      "headers": [
        {
          "level": 2,
          "title": "前端部署",
          "slug": "前端部署"
        },
        {
          "level": 2,
          "title": "前端部署1",
          "slug": "前端部署1"
        },
        {
          "level": 3,
          "title": "123",
          "slug": "_123"
        }
      ],
      "lastUpdated": "2023年8月4日",
      "lastUpdatedTimestamp": 1691161414000
    }
  ],
  "themeConfig": {
    "logo": "/assets/img/avatar.jpg",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "vuePress使用",
        "link": "/vuePress/"
      },
      {
        "text": "前端",
        "items": [
          {
            "text": "javascript",
            "link": "/web/javascript/"
          },
          {
            "text": "css",
            "link": "/web/css/"
          },
          {
            "text": "vue",
            "link": "/web/vue/"
          },
          {
            "text": "element-ui",
            "link": "/web/element-ui/"
          },
          {
            "text": "echarts",
            "link": "/web/echarts/"
          },
          {
            "text": "webpack",
            "link": "/web/webpack/"
          },
          {
            "text": "nodejs",
            "link": "/web/nodejs/"
          },
          {
            "text": "前端部署那些事",
            "link": "/web/webDescription/"
          },
          {
            "text": "前端有趣的插件",
            "link": "/web/plugins/"
          }
        ]
      },
      {
        "text": "花花日记",
        "items": [
          {
            "text": "罗老师金典名言",
            "link": "/"
          },
          {
            "text": "走心文案",
            "link": "/dayRecord/heart/"
          }
        ]
      },
      {
        "text": "博客",
        "link": "https://huaxiaobao.top"
      },
      {
        "text": "语言",
        "link": "/language/"
      }
    ],
    "sidebar": {
      "/vuePress/": [
        "/vuePress/",
        "/vuePress/gitOpreation/",
        "/vuePress/vuePressGuide/",
        "/vuePress/navigationGuide/",
        "/vuePress/sidebarGuide/",
        "/vuePress/componentGuide/",
        "/vuePress/vendorGuide/",
        "/vuePress/githubFBGuide/",
        "/vuePress/pwaGuide/"
      ],
      "/language/": [
        "chinese",
        "english"
      ],
      "/web/javascript/": [
        "/web/javascript/"
      ]
    },
    "lastUpdated": "更新时间",
    "searchMaxSuggestions": 10
  }
}